application:
  subdomain: v2raya
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://host.lzcapp:2017
  ingress:
    - protocol: tcp
      port: 20170
      service: v2raya
    - protocol: tcp
      port: 20171
      service: v2raya
    - protocol: tcp
      port: 20172
      service: v2raya
  health_check:
    test_url: http://host.lzcapp:2017
    start_period: 10s
services:
  v2raya:
    # upstream: mzz2017/v2raya:v2.5.7
    image: docker.1panel.live/mzz2017/v2raya:v2.5.7
    environment:
      - V2RAYA_ADDRESS=host.lzcapp:2017
      - V2RAYA_NFTABLES_SUPPORT=off
      - V2RAYA_LOG_FILE=/var/v2raya.log
    network_mode: host
    netadmin: true
    binds:
      - /lzcapp/cache:/var
      - /lzcapp/var:/etc/v2raya
